src/Entity/Covoiturage.php
<?php

namespace App\Entity;

use App\Repository\CovoiturageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CovoiturageRepository::class)]
class Covoiturage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    /**
     * @var Collection<int, Utilisateur>
     */
    #[ORM\ManyToMany(targetEntity: Utilisateur::class, mappedBy: 'participations')]
    private Collection $participants;

    #[ORM\ManyToOne(inversedBy: 'covoiturages')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Voiture $voiture = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $date_depart = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTime $heure_depart = null;

    #[ORM\Column(length: 255)]
    private ?string $lieu_depart = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $date_arrivee = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTime $heure_arrivee = null;

    #[ORM\Column(length: 255)]
    private ?string $lieu_arrivee = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $statut = null;

    #[ORM\Column]
    private ?int $nb_place = null;

    #[ORM\Column]
    private ?float $prix_personne = null;

//ajout relation avec user qui crée le trajet
    #[ORM\ManyToOne(inversedBy: 'trajetsProposes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Utilisateur $user = null;


    public function __construct()
    {
        $this->participants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection<int, Utilisateur>
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(Utilisateur $participant): static
    {
        if (!$this->participants->contains($participant)) {
            $this->participants->add($participant);
            $participant->addParticipation($this);
        }

        return $this;
    }

    public function removeParticipant(Utilisateur $participant): static
    {
        if ($this->participants->removeElement($participant)) {
            $participant->removeParticipation($this);
        }

        return $this;
    }

    public function getVoiture(): ?Voiture
    {
        return $this->voiture;
    }

    public function setVoiture(?Voiture $voiture): static
    {
        $this->voiture = $voiture;

        return $this;
    }

    public function getDateDepart(): ?\DateTime
    {
        return $this->date_depart;
    }

    public function setDateDepart(\DateTime $date_depart): static
    {
        $this->date_depart = $date_depart;

        return $this;
    }

    public function getHeureDepart(): ?\DateTime
    {
        return $this->heure_depart;
    }

    public function setHeureDepart(\DateTime $heure_depart): static
    {
        $this->heure_depart = $heure_depart;

        return $this;
    }

    public function getLieuDepart(): ?string
    {
        return $this->lieu_depart;
    }

    public function setLieuDepart(string $lieu_depart): static
    {
        $this->lieu_depart = $lieu_depart;

        return $this;
    }

    public function getDateArrivee(): ?\DateTime
    {
        return $this->date_arrivee;
    }

    public function setDateArrivee(\DateTime $date_arrivee): static
    {
        $this->date_arrivee = $date_arrivee;

        return $this;
    }

    public function getHeureArrivee(): ?\DateTime
    {
        return $this->heure_arrivee;
    }

    public function setHeureArrivee(\DateTime $heure_arrivee): static
    {
        $this->heure_arrivee = $heure_arrivee;

        return $this;
    }

    public function getLieuArrivee(): ?string
    {
        return $this->lieu_arrivee;
    }

    public function setLieuArrivee(string $lieu_arrivee): static
    {
        $this->lieu_arrivee = $lieu_arrivee;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(?string $statut): static
    {
        $this->statut = $statut;

        return $this;
    }

    public function getNbPlace(): ?float
    {
        return $this->nb_place;
    }

    public function setNbPlace(float $nb_place): static
    {
        $this->nb_place = $nb_place;

        return $this;
    }

    public function getPrixPersonne(): ?float
    {
        return $this->prix_personne;
    }

    public function setPrixPersonne(float $prix_personne): static
    {
        $this->prix_personne = $prix_personne;

        return $this;
    }

    public function getUser(): ?Utilisateur
    {
        return $this->user;
    }

    public function setUser(?Utilisateur $user): static
    {
        $this->user = $user;

        return $this;
    }


}

src/Form/CovoiturageType.php
<?php

namespace App\Form;

use App\Entity\Covoiturage;
use App\Entity\Utilisateur;
use App\Entity\Voiture;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CovoiturageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_depart')
            ->add('heure_depart')
            ->add('lieu_depart')
            ->add('date_arrivee')
            ->add('heure_arrivee')
            ->add('lieu_arrivee')
            // ->add('statut')
            ->add('nb_place')
            ->add('prix_personne')
            // ->add('participants', EntityType::class, [
            //     'class' => Utilisateur::class,
            //     'choice_label' => 'id',
            //     'multiple' => true,
            // ])
            // ->add('user')
            ->add('voiture', EntityType::class, [
                'class' => Voiture::class,
                'choice_label' => 'modele',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Covoiturage::class,
        ]);
    }
}

src/Controller/CovoiturageController.php
<?php

namespace App\Controller;

use App\Entity\Covoiturage;
use App\Form\CovoiturageType;
use App\Repository\CovoiturageRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\JsonResponse;

#[Route('/covoiturage')]
final class CovoiturageController extends AbstractController
{
    #[Route(name: 'app_covoiturage_index', methods: ['GET'])]
    public function index(Request $request , CovoiturageRepository $covoiturageRepository): Response
    {
        $covoiturages = $covoiturageRepository->findAll();
        return $this->render('covoiturage/index.html.twig', [
            'covoiturages' => $covoiturages,
        ]);
    }

    #[Route('/new', name: 'app_covoiturage_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $covoiturage = new Covoiturage();
        $form = $this->createForm(CovoiturageType::class, $covoiturage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $user = $this->getUser();
            $covoiturage->setUser($user); 

            $entityManager->persist($covoiturage);
            $entityManager->flush();

            return $this->redirectToRoute('app_covoiturage_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('covoiturage/new.html.twig', [
            'covoiturage' => $covoiturage,
            'form' => $form,
        ]);
    }

    /**
     * Gets the filtered cars
     *
     * @param Request $request The current request
     * @param CovoiturageRepository $covoiturageRepository The Covoiturage Repository
     * @return JsonResponse An array with all covoits ids and filtered covoits ids
     */
   
    #[Route('/getCovoitRecherches', name: 'getCovoitRecherches', methods: ['GET'])]
    public function getCovoitRecherches(Request $request, CovoiturageRepository $covoitRepository): JsonResponse
    {
        // Get filter information
        $depart = $request->query->get('depart');
        $arrivee = $request->query->get('arrivee');
        $date = $request->query->get('date');
        

        // Get filtered car covoits
        // J'ai renommé $covoiturageRepository en $covoitRepository dans la signature
        $repoFielteredCovoits = $covoitRepository->findFilteredCovoits(
            $depart,
            $arrivee,
            $date,
        );
        $filteredCovoits = [];
        foreach ($repoFielteredCovoits as $filteredCovoit) {
            array_push($filteredCovoits, $filteredCovoit);
        }

        return $this->json($filteredCovoits);
    }


    #[Route('/{id}', name: 'app_covoiturage_show', methods: ['GET'])]
    public function show(Covoiturage $covoiturage): Response
    {
        return $this->render('covoiturage/show.html.twig', [
            'covoiturage' => $covoiturage,
        ]);
    }

    // reservation d'un trajet de covoit 
    // src/Controller/CovoiturageController.php

// ...

#[Route('/covoiturage/{id}/reserver', name: 'app_covoiturage_reserver', methods: ['POST'])]
public function reserver(Covoiturage $covoiturage, EntityManagerInterface $entityManager): Response
{
    // 1. Vérification de l'authentification (Sécurité)
    if (!$this->getUser()) {
        $this->addFlash('error', 'Vous devez être connecté pour réserver un trajet.');
        return $this->redirectToRoute('app_login'); // Rediriger vers la connexion
    }
    
    $user = $this->getUser();

    // 2. Vérification de la disponibilité des places
    $placesDisponibles = $covoiturage->getNbPlace();
    
    if ($placesDisponibles <= 0) {
        $this->addFlash('error', 'Désolé, il n\'y a plus de places disponibles pour ce trajet.');
        return $this->redirectToRoute('app_covoiturage_index'); 
    }

    // 3. Vérification que l'utilisateur n'a pas déjà réservé
    if ($covoiturage->getParticipants()->contains($user)) {
        $this->addFlash('error', 'Vous avez déjà réservé une place pour ce trajet.');
        return $this->redirectToRoute('app_covoiturage_index');
    }

    
    $covoiturage->addParticipant($user);

    // B. Décrémenter le nombre de places disponibles
    $covoiturage->setNbPlace($placesDisponibles - 1);

    // 5. Sauvegarder en base de données
    $entityManager->flush();

    $this->addFlash('success', 'Réservation effectuée avec succès ! Une place a été déduite.');

    return $this->redirectToRoute('app_covoiturage_index'); 
} 


    #[Route('/{id}/edit', name: 'app_covoiturage_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Covoiturage $covoiturage, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CovoiturageType::class, $covoiturage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_covoiturage_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('covoiturage/edit.html.twig', [
            'covoiturage' => $covoiturage,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_covoiturage_delete', methods: ['POST'])]
    public function delete(Request $request, Covoiturage $covoiturage, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$covoiturage->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($covoiturage);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_covoiturage_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/covoiturage/_delete_form.html.twig
<form method="post" action="{{ path('app_covoiturage_delete', {'id': covoiturage.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ covoiturage.id) }}">
	<button class="btn">Supprimer</button>
	{% include 'footer.html.twig' %}
</form>

templates/covoiturage/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/covoiturage/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
	{% include 'navbar.html.twig' %}
	<div class="container my-5">
		<div class="card p-4 shadow mb-5">
			<div class="row justify-content-center">
				<h1>Edit Covoiturage</h1>

				{{ include('covoiturage/_form.html.twig', {'button_label': 'Reserver'}) }}

				<a href="{{ path('app_covoiturage_index') }}">Retour à la liste</a>

			</div>
		</div>
	</div>
	{% include 'footer.html.twig' %}
{% endblock %}

templates/covoiturage/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Covoiturages
{% endblock %}

{% block body %}
	{% include 'navbar.html.twig' %}
	<div class="container my-5">
		<h1 class="mb-4">Trouver un covoiturage</h1>


		<div class="card p-4 shadow mb-5">
			<div class="row justify-content-center">
				<div class="col">
					<input id="depart" class="form-control" placeholder="Lieu de départ" type="text">
				</div>
				<div class="col">
					<input id="arrivee" class="form-control" placeholder="Lieu d'arrivée" type="text">
				</div>
				<div class="col">
					<input id="date" class="form-control" type="date">
				</div>
			</div>
			<div class="text-center mt-4">
				<button class="btn btn-primary btn-lg" id="recherche">Rechercher</button>
			</div>
		</div>

		<h2 id="covoitNumbers" class="mt-5">Résultats de la recherche ({{ covoiturages|length }})</h2>

		<div class="table-responsive">
			<table class="table table-striped table-hover">
				<thead class="table-dark">
					<tr>
						<th>Départ</th>
						<th>Arrivée</th>
						<th>Date de départ</th>
						<th>Heure de départ</th>
						<th>Places disponibles</th>
						<th>Prix par personne</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody id="covoiturages">
					{% for covoiturage in covoiturages %}
						<tr>
							<td>{{ covoiturage.lieuDepart }}</td>
							<td>{{ covoiturage.lieuArrivee }}</td>
							<td>{{ covoiturage.dateDepart ? covoiturage.dateDepart|date('d/m/Y') : '' }}</td>
							<td>{{ covoiturage.heureDepart ? covoiturage.heureDepart|date('H:i') : '' }}</td>
							<td>{{ covoiturage.nbPlace }}</td>
							<td>{{ covoiturage.prixPersonne }}
								€</td>
							<td>
								<a href="{{ path('app_covoiturage_show', {'id': covoiturage.id}) }}" class="btn btn-info btn-sm">Voir</a>


								{% if app.user %}

									<form method="POST" action="{{ path('app_covoiturage_reserver', {'id': covoiturage.id}) }}" style="display:inline-block;">

										<input type="hidden" name="_token" value="{{ csrf_token('reserver' ~ covoiturage.id) }}">

										<button type="submit" class="btn btn-warning btn-sm">
											Réserver
										</button>
									</form>
								{% else %}
									<a href="{{ path('app_login') }}" class="btn btn-warning btn-sm" title="Connectez-vous pour réserver">Réserver</a>
								{% endif %}

							</td>
						</tr>
					{% else %}
						<tr>
							<td colspan="7" class="text-center">Aucun covoiturage ne correspond à vos critères de recherche.</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>

		<div class="text-center mt-4">
			<a href="{{ path('app_covoiturage_new') }}" class="btn btn-success">Créer un covoiturage</a>
		</div>
	</div>
	{% block javascripts %}
		<script src="https://cdn.jsdelivr.net/npm/jquery-ajax@2.1.4/jquery.min.js"></script>
		<script src="{{ asset('js/filter.js') }}"></script>
	{% endblock %}
	{% include 'footer.html.twig' %}
{% endblock %}

templates/covoiturage/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
	{% include 'navbar.html.twig' %}
	<div class="container my-5 bg-body rounded">
		<div class="row">
			<div class="col-12">
				<h1>Créer un nouveau Covoiturage</h1>

				{{ include('covoiturage/_form.html.twig') }}

				<a href="{{ path('app_covoiturage_index') }}">Retour</a>
			</div>
		</div>
	</div>
	{% include 'footer.html.twig' %}
{% endblock %}

templates/covoiturage/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails du Covoiturage
{% endblock %}

{% block body %}
	{% include 'navbar.html.twig' %}
	<div class="container my-5">
		<h1 class="mb-4 text-primary">Détails du Trajet</h1>

		<div class="card shadow p-4 mb-4">
			<h2 class="card-title text-center mb-4">{{ covoiturage.lieuDepart }}
				<i class="fas fa-arrow-right mx-2"></i>
				{{ covoiturage.lieuArrivee }}</h2>

			<div class="row">
				<div class="col-md-6">
					<h5 class="text-secondary">Informations Clés</h5>
					<ul class="list-group list-group-flush">
						<li class="list-group-item">
							<strong>Date:</strong>
							{{ covoiturage.dateDepart ? covoiturage.dateDepart|date('d/m/Y') : 'N/A' }}</li>
						<li class="list-group-item">
							<strong>Heure:</strong>
							{{ covoiturage.heureDepart ? covoiturage.heureDepart|date('H:i') : 'N/A' }}</li>
						<li class="list-group-item">
							<strong>Places disponibles:</strong>
							<span class="badge bg-{{ covoiturage.nbPlace > 0 ? 'success' : 'danger' }}">{{ covoiturage.nbPlace }}</span>
						</li>
						<li class="list-group-item">
							<strong>Prix par personne:</strong>
							<span class="fw-bold">{{ covoiturage.prixPersonne }}
								€</span>
						</li>
					</ul>
				</div>

				<div class="col-md-6 mt-4 mt-md-0">
					<h5 class="text-secondary">Informations sur le Conducteur</h5>
					<ul class="list-group list-group-flush">

						<li class="list-group-item">
							<strong>Nom:</strong>
							{{ covoiturage.user.prenom|default('N/A') }}
							{{ covoiturage.user.nom|default('') }}</li>
						<li class="list-group-item">
							<strong>Voiture:</strong>
							{{ covoiturage.voitureModele|default('Non spécifié') }}</li>
						<li class="list-group-item">
							<strong>Contact:</strong>
							<a href="mailto:{{ covoiturage.user.email }}">{{ covoiturage.user.email }}</a>
						</li>
					</ul>
				</div>
			</div>

		</div>


		<div class="card p-4 shadow mt-5 bg-light">
			<h3 class="mb-3">Action de Réservation</h3>

			{% if app.user %}

				{% set estDejaInscrit = covoiturage.participants is defined and covoiturage.participants.contains(app.user) %}
				{% set placesEpuisees = covoiturage.nbPlace <= 0 %}
				{% set estConducteur = covoiturage.user == app.user %}
				{% set isFormDisabled = estConducteur or estDejaInscrit or placesEpuisees %}

				{% if estConducteur %}
					<div class="alert alert-info">Vous êtes le conducteur de ce trajet.</div>
				{% elseif estDejaInscrit %}
					<div class="alert alert-success">Vous êtes déjà inscrit pour ce trajet !</div>
				{% elseif placesEpuisees %}
					<div class="alert alert-danger">Désolé, ce trajet est complet.</div>
				{% else %}

					<form method="POST" action="{{ path('app_covoiturage_show', {'id': covoiturage.id}) }}" onsubmit="return confirm('Confirmez-vous la réservation de 1 place pour ce trajet ?');">
						<input type="hidden" name="_token" value="{{ csrf_token('reserver' ~ covoiturage.id) }}">
						<p>
							" Réserver"votre place.</p>
						<button type="submit" class="btn btn-warning btn-lg w-100">
							Confirmer la Réservation (1 place -
							{{ covoiturage.prixPersonne }}
							€)
						</button>
					</form>
				{% endif %}
			{% else %}
				<div class="alert alert-warning text-center">
					<a href="{{ path('app_login') }}" class="btn btn-warning btn-lg">Connectez-vous</a>
					pour pouvoir réserver votre place.
				</div>
			{% endif %}

			<a href="{{ path('app_covoiturage_index') }}" class="btn btn-outline-secondary mt-3">Retour à la liste</a>
		</div>
	</div>
	{% include 'footer.html.twig' %}
{% endblock %}